### ISSUE TITLE
All works assigned to a certain contact

### ISSUE THREAD

**Issue by fkleinman** [altimetrik-onboarding-uy/fkleinman#18]
As a user i need to see all work items assigned to a certain contact inside the contact’s detail page

**Comment by fkleinman** [comment]
@rjulianialtimetrik i dont really understand this one. I have to create a new tab with this information asked?

**Comment by rjulianialtimetrik** [comment]
The idea here is that inside the Contact Detail Page you insert your main work manager lightning component and based on context information (the Contact the user is looking at) the component only shows work items assigned to that contact.
